import {test,expect} from './fixtures';
import {chooseSwitch,startSwitch} from './switch-helpers';
test.beforeEach(async({serviceWorker})=>{await serviceWorker.evaluate(async()=>chrome.storage.local.set({switchSettings:{schemaVersion:1,mode:'switch',intervalMs:800,protectionMs:100}}));});
const html=`<form onsubmit="window.submits++;return false"><label>관심 주제<select id="topics" multiple><option value="private-a" selected>가</option><option value="private-b">나</option><optgroup label="고정" disabled><option selected>다</option></optgroup></select></label><button>제출</button></form><script>window.inputs=0;window.changes=0;window.clicks=0;window.submits=0;document.addEventListener('input',()=>window.inputs++);document.addEventListener('change',()=>window.changes++);document.addEventListener('click',()=>window.clicks++);</script>`;
test('Space accumulates a multiple proposal and applies once while preserving disabled choices and privacy',async({context,servePage,serviceWorker,expectNoExternalRequests})=>{
 test.setTimeout(130000);servePage('http://practice.test/multiple.html',html);const page=await context.newPage();await page.goto('http://practice.test/multiple.html');await startSwitch(page);await chooseSwitch(page,'페이지 항목');await chooseSwitch(page,'관심 주제');
 const panel=page.locator('tremor-helper-root').locator('.switch-panel');await expect(panel.locator('h2')).toContainText('여러 항목 고르기');await expect(panel).toContainText('다 · 변경할 수 없음');await expect(panel.locator('[data-item-id="control-option:2"]')).toHaveCount(0);
 await chooseSwitch(page,'2. 나 · 선택하기');await chooseSwitch(page,'1. 가 · 선택 해제하기');expect(await page.locator('#topics').evaluate((el:HTMLSelectElement)=>Array.from(el.selectedOptions).map(o=>o.text))).toEqual(['가','다']);
 for(const width of [360,768,1280]){await page.setViewportSize({width,height:800});const metrics=await panel.evaluate(el=>({right:el.getBoundingClientRect().right,bottom:el.getBoundingClientRect().bottom,previewFits:(el.querySelector('.switch-draft')?.scrollHeight??0)<=(el.querySelector('.switch-draft')?.clientHeight??0),choices:Array.from(el.querySelectorAll('.switch-choice')).map(choice=>({height:choice.getBoundingClientRect().height,font:parseFloat(getComputedStyle(choice).fontSize)}))}));expect(metrics.previewFits).toBe(true);expect(metrics.right).toBeLessThanOrEqual(width);expect(metrics.bottom).toBeLessThanOrEqual(800);for(const choice of metrics.choices){expect(choice.height).toBeGreaterThanOrEqual(56);expect(choice.font).toBeGreaterThanOrEqual(18);}}
 await chooseSwitch(page,'선택 적용');expect(await page.locator('#topics').evaluate((el:HTMLSelectElement)=>Array.from(el.selectedOptions).map(o=>o.text))).toEqual(['나','다']);await chooseSwitch(page,'1. 가 · 선택하기');await chooseSwitch(page,'선택 적용');expect(await page.locator('#topics').evaluate((el:HTMLSelectElement)=>Array.from(el.selectedOptions).map(o=>o.text))).toEqual(['가','나','다']);
 expect(await page.evaluate(()=>{const w=window as Window&{inputs?:number;changes?:number;clicks?:number;submits?:number};return [w.inputs,w.changes,w.clicks,w.submits];})).toEqual([2,2,0,0]);expect(await serviceWorker.evaluate(async()=>JSON.stringify([await chrome.storage.local.get(null),await chrome.storage.session.get(null)]))).not.toContain('private-');expectNoExternalRequests();
});
test('multiple selection refuses external changes and removed-reinserted options',async({context,servePage})=>{
 test.setTimeout(140000);servePage('http://practice.test/multiple-change.html',html);const page=await context.newPage();await page.goto('http://practice.test/multiple-change.html');await startSwitch(page);await chooseSwitch(page,'글쓰기');await chooseSwitch(page,'양식 한 장 보기');await chooseSwitch(page,'관심 주제');await chooseSwitch(page,'2. 나 · 선택하기');
 await page.locator('#topics').evaluate((el:HTMLSelectElement)=>{const option=el.options[0];if(!option)throw new Error('missing option');option.selected=false;});await chooseSwitch(page,'선택 적용');const panel=page.locator('tremor-helper-root').locator('.switch-panel');await expect(panel).toContainText('선택칸이 바뀌었어요');expect(await page.locator('#topics').evaluate((el:HTMLSelectElement)=>Array.from(el.selectedOptions).map(o=>o.text))).toEqual(['다']);
 await chooseSwitch(page,'양식 목록');await chooseSwitch(page,'관심 주제');await chooseSwitch(page,'2. 나 · 선택하기');await page.locator('#topics').evaluate((el:HTMLSelectElement)=>{const node=el.options[1];if(!node)throw new Error('missing option');const next=node.nextSibling;node.remove();el.insertBefore(node,next);});await chooseSwitch(page,'선택 적용');await expect(panel).toContainText('선택칸이 바뀌었어요');expect(await page.evaluate(()=>(window as Window&{changes?:number}).changes)).toBe(0);
});
test('multiple pause preserves the writing draft and requires a fresh field before explicit empty apply',async({context,servePage})=>{
 test.setTimeout(140000);servePage('http://practice.test/multiple-rest.html',html.replace('<optgroup label="고정" disabled><option selected>다</option></optgroup>',''));const page=await context.newPage();await page.goto('http://practice.test/multiple-rest.html');await startSwitch(page);await chooseSwitch(page,'글쓰기');await chooseSwitch(page,'새 문장');await chooseSwitch(page,'띄어쓰기');await chooseSwitch(page,'양식 한 장 보기');await chooseSwitch(page,'관심 주제');await chooseSwitch(page,'2. 나 · 선택하기');await chooseSwitch(page,'쉬기');await page.keyboard.press('Space');await page.waitForTimeout(125);await chooseSwitch(page,'관심 주제');await chooseSwitch(page,'1. 가 · 선택 해제하기');await chooseSwitch(page,'선택 적용');expect(await page.locator('#topics').evaluate((el:HTMLSelectElement)=>el.selectedOptions.length)).toBe(0);await chooseSwitch(page,'원래 화면으로');await expect(page.locator('tremor-helper-root').locator('.switch-draft')).toContainText(' ');
});
test('lost multiple acknowledgement pauses and never repeats the committed selection',async({context,servePage,serviceWorker})=>{
 test.setTimeout(100000);servePage('http://practice.test/multiple-unknown.html',html);const page=await context.newPage();await page.goto('http://practice.test/multiple-unknown.html');await startSwitch(page);await chooseSwitch(page,'글쓰기');await chooseSwitch(page,'양식 한 장 보기');await chooseSwitch(page,'관심 주제');await chooseSwitch(page,'2. 나 · 선택하기');
 await serviceWorker.evaluate(()=>{const send=chrome.tabs.sendMessage.bind(chrome.tabs);chrome.tabs.sendMessage=async(tabId,message,options)=>{const reply=await send(tabId,message,options);if(typeof message==='object'&&message!==null&&'action' in message&&typeof message.action==='object'&&message.action!==null&&'kind' in message.action&&message.action.kind==='applyControl')return {result:'unknown'};return reply;};});
 await chooseSwitch(page,'선택 적용');const panel=page.locator('tremor-helper-root').locator('.switch-panel');await expect(panel).toHaveAttribute('data-mode','paused');await expect(panel).toContainText('실행 결과를 확인하세요');await page.keyboard.press('Space');await page.waitForTimeout(125);await expect(panel.locator('[data-item-id="control-apply"]')).toHaveCount(0);expect(await page.evaluate(()=>(window as Window&{changes?:number}).changes)).toBe(1);
});
test('multiple rejects removing and reinserting its external form owner',async({context,servePage})=>{
 test.setTimeout(100000);servePage('http://practice.test/multiple-owner.html','<form id="owner"></form><select id="topics" form="owner" multiple aria-label="관심 주제"><option selected>가</option><option>나</option></select><script>window.changes=0;document.addEventListener("change",()=>window.changes++);</script>');const page=await context.newPage();await page.goto('http://practice.test/multiple-owner.html');await startSwitch(page);await chooseSwitch(page,'글쓰기');await chooseSwitch(page,'양식 한 장 보기');await chooseSwitch(page,'관심 주제');await chooseSwitch(page,'2. 나 · 선택하기');await page.locator('#owner').evaluate(el=>{el.remove();document.body.prepend(el);});await chooseSwitch(page,'선택 적용');await expect(page.locator('tremor-helper-root').locator('.switch-panel')).toContainText('선택칸이 바뀌었어요');expect(await page.locator('#topics').evaluate((el:HTMLSelectElement)=>Array.from(el.selectedOptions).map(o=>o.text))).toEqual(['가']);expect(await page.evaluate(()=>(window as Window&{changes?:number}).changes)).toBe(0);
});
test('multiple option pages keep long duplicate labels numbered and readable at narrow widths',async({context,servePage})=>{
 test.setTimeout(120000);const label='긴 항목 '.repeat(8)+'끝';servePage('http://practice.test/multiple-long.html',`<select multiple aria-label="관심 주제"><option selected>${label}</option>${Array.from({length:6},(_,index)=>`<option>${index===5?label:'항목 '+String(index)}</option>`).join('')}</select>`);const page=await context.newPage();await page.goto('http://practice.test/multiple-long.html');await startSwitch(page);await chooseSwitch(page,'페이지 항목');await chooseSwitch(page,'관심 주제');await chooseSwitch(page,'다음 선택 묶음');await chooseSwitch(page,`7. ${Array.from(label).slice(0,24).join('')}… · 선택하기`);
 const panel=page.locator('tremor-helper-root').locator('.switch-panel');const pages=[await panel.locator('.switch-draft').innerText()];while(await panel.locator('[data-item-id="control-preview-next"]').count()){await chooseSwitch(page,'다음 항목 읽기');pages.push(await panel.locator('.switch-draft').innerText());}expect(pages.map(text=>text.split('\n').slice(1).join('\n')).join('')).toBe('1. '+label+' / 7. '+label);
 for(const width of [360,768,1280]){await page.setViewportSize({width,height:800});const metrics=await panel.evaluate(el=>({right:el.getBoundingClientRect().right,bottom:el.getBoundingClientRect().bottom,overflow:Array.from(el.querySelectorAll('.switch-draft,.switch-choice')).some(node=>node.scrollWidth>node.clientWidth)}));expect(metrics.right).toBeLessThanOrEqual(width);expect(metrics.bottom).toBeLessThanOrEqual(800);expect(metrics.overflow).toBe(false);}
 await chooseSwitch(page,'선택 적용');expect(await page.locator('select').evaluate((el:HTMLSelectElement)=>Array.from(el.options).flatMap((option,index)=>option.selected?[index]:[]))).toEqual([0,6]);
});
test('multiple site event changing the field meaning is refused without replay',async({context,servePage})=>{
 test.setTimeout(85000);servePage('http://practice.test/multiple-meaning.html',html);const page=await context.newPage();await page.goto('http://practice.test/multiple-meaning.html');await startSwitch(page);await chooseSwitch(page,'페이지 항목');await chooseSwitch(page,'관심 주제');await chooseSwitch(page,'2. 나 · 선택하기');await page.locator('#topics').evaluate(el=>{el.addEventListener('input',()=>{el.setAttribute('aria-label','다른 목적');});});await chooseSwitch(page,'선택 적용');const panel=page.locator('tremor-helper-root').locator('.switch-panel');await expect(panel).toContainText('선택칸이 바뀌었어요');await expect(panel.locator('[data-item-id="control-apply"]')).toHaveCount(0);expect(await page.evaluate(()=>(window as Window&{changes?:number}).changes)).toBe(1);
});
