import {test,expect} from './fixtures';
import {chooseSwitch,startSwitch} from './switch-helpers';
test.beforeEach(async({serviceWorker})=>{await serviceWorker.evaluate(async()=>chrome.storage.local.set({switchSettings:{schemaVersion:1,mode:'switch',intervalMs:800,protectionMs:100}}));});
const html=`<form id="delivery" onsubmit="window.submits++;return false"><label><input id="visit" type="radio" name="delivery" value="private-visit" checked>방문</label><label><input id="mail" type="radio" name="delivery" value="private-mail">우편</label><button>제출</button></form><label><input id="external" type="radio" form="delivery" name="delivery" value="private-external">보관함</label><form><label><input id="other" type="radio" name="delivery" checked>다른 양식</label></form><script>window.inputs=0;window.changes=0;window.clicks=0;window.submits=0;document.addEventListener('input',()=>window.inputs++);document.addEventListener('change',()=>window.changes++);document.addEventListener('click',()=>window.clicks++);</script>`;
test('Space proposes and explicitly applies a radio choice without clicking, submitting or storing values',async({context,servePage,serviceWorker,expectNoExternalRequests})=>{
 test.setTimeout(110000);servePage('http://practice.test/radio.html',html);const page=await context.newPage();await page.goto('http://practice.test/radio.html');await startSwitch(page);await chooseSwitch(page,'페이지 항목');await chooseSwitch(page,'우편');
 const panel=page.locator('tremor-helper-root').locator('.switch-panel');await expect(panel.locator('h2')).toContainText('하나만 고르는 항목');await expect(panel).toContainText('선택 안 됨');await chooseSwitch(page,'이 항목 선택');await expect(page.locator('#mail')).not.toBeChecked();await expect(page.locator('#visit')).toBeChecked();
 for(const width of [360,768,1280]){await page.setViewportSize({width,height:800});const metrics=await panel.evaluate(el=>({right:el.getBoundingClientRect().right,bottom:el.getBoundingClientRect().bottom,previewFits:(el.querySelector('.switch-draft')?.scrollHeight??0)<=(el.querySelector('.switch-draft')?.clientHeight??0),choices:Array.from(el.querySelectorAll('.switch-choice')).map(choice=>({height:choice.getBoundingClientRect().height,font:parseFloat(getComputedStyle(choice).fontSize)}))}));expect(metrics.previewFits).toBe(true);expect(metrics.right).toBeLessThanOrEqual(width);expect(metrics.bottom).toBeLessThanOrEqual(800);for(const choice of metrics.choices){expect(choice.height).toBeGreaterThanOrEqual(56);expect(choice.font).toBeGreaterThanOrEqual(18);}}
 await chooseSwitch(page,'선택 적용');await expect(page.locator('#mail')).toBeChecked();await expect(page.locator('#visit')).not.toBeChecked();await expect(page.locator('#other')).toBeChecked();await expect(panel.locator('[data-item-id="control-radio"]')).toHaveCount(0);
 expect(await page.evaluate(()=>{const w=window as Window&{inputs?:number;changes?:number;clicks?:number;submits?:number};return [w.inputs,w.changes,w.clicks,w.submits];})).toEqual([1,1,0,0]);
 expect(await serviceWorker.evaluate(async()=>JSON.stringify([await chrome.storage.local.get(null),await chrome.storage.session.get(null)]))).not.toContain('private-');expectNoExternalRequests();
});
test('external form-associated radio changes and removed-reinserted members invalidate the proposal',async({context,servePage})=>{
 test.setTimeout(150000);servePage('http://practice.test/radio-change.html',html);const page=await context.newPage();await page.goto('http://practice.test/radio-change.html');await startSwitch(page);await chooseSwitch(page,'글쓰기');await chooseSwitch(page,'양식 한 장 보기');await chooseSwitch(page,'우편');await chooseSwitch(page,'이 항목 선택');
 await page.locator('#external').evaluate((el:HTMLInputElement)=>{el.checked=true;});await chooseSwitch(page,'선택 적용');await expect(page.locator('#mail')).not.toBeChecked();await expect(page.locator('#external')).toBeChecked();
 const panel=page.locator('tremor-helper-root').locator('.switch-panel');await expect(panel).toContainText('선택칸이 바뀌었어요');await chooseSwitch(page,'양식 목록');await chooseSwitch(page,'우편');await chooseSwitch(page,'이 항목 선택');
 await page.locator('#visit').evaluate(el=>{const parent=el.parentNode;if(parent){el.remove();parent.prepend(el);}});await chooseSwitch(page,'선택 적용');await expect(page.locator('#mail')).not.toBeChecked();await expect(page.locator('#external')).toBeChecked();
});
test('radio pause requires a fresh field choice and preserves the original writing draft',async({context,servePage})=>{
 test.setTimeout(150000);servePage('http://practice.test/radio-rest.html',html);const page=await context.newPage();await page.goto('http://practice.test/radio-rest.html');await startSwitch(page);await chooseSwitch(page,'글쓰기');await chooseSwitch(page,'새 문장');await chooseSwitch(page,'띄어쓰기');await chooseSwitch(page,'양식 한 장 보기');await chooseSwitch(page,'우편');await chooseSwitch(page,'이 항목 선택');await chooseSwitch(page,'쉬기');
 await page.keyboard.press('Space');await page.waitForTimeout(125);await expect(page.locator('#mail')).not.toBeChecked();await chooseSwitch(page,'우편');await chooseSwitch(page,'이 항목 선택');await chooseSwitch(page,'선택 적용');await expect(page.locator('#mail')).toBeChecked();await chooseSwitch(page,'원래 화면으로');await expect(page.locator('tremor-helper-root').locator('.switch-draft')).toContainText(' ');
});
test('lost radio acknowledgement pauses and never retries the completed group change',async({context,servePage,serviceWorker})=>{
 test.setTimeout(100000);servePage('http://practice.test/radio-unknown.html',html);const page=await context.newPage();await page.goto('http://practice.test/radio-unknown.html');await startSwitch(page);await chooseSwitch(page,'글쓰기');await chooseSwitch(page,'양식 한 장 보기');await chooseSwitch(page,'우편');await chooseSwitch(page,'이 항목 선택');
 await serviceWorker.evaluate(()=>{const send=chrome.tabs.sendMessage.bind(chrome.tabs);chrome.tabs.sendMessage=async(tabId,message,options)=>{const reply=await send(tabId,message,options);if(typeof message==='object'&&message!==null&&'action' in message&&typeof message.action==='object'&&message.action!==null&&'kind' in message.action&&message.action.kind==='applyControl')return {result:'unknown'};return reply;};});
 await chooseSwitch(page,'선택 적용');const panel=page.locator('tremor-helper-root').locator('.switch-panel');await expect(panel).toHaveAttribute('data-mode','paused');await expect(panel).toContainText('실행 결과를 확인하세요');await page.keyboard.press('Space');await page.waitForTimeout(125);await expect(page.locator('#mail')).toBeChecked();await expect(panel.locator('[data-item-id="control-apply"]')).toHaveCount(0);expect(await page.evaluate(()=>(window as Window&{changes?:number}).changes)).toBe(1);
});
