import {test,expect} from './fixtures';
import {chooseSwitch,startSwitch} from './switch-helpers';
test.beforeEach(async({serviceWorker})=>{await serviceWorker.evaluate(async()=>chrome.storage.local.set({switchSettings:{schemaVersion:1,mode:'switch',intervalMs:800,protectionMs:100}}));});
const html=`<form onsubmit="window.submits++;return false"><label>분류<select id="category"><option value="secret-a">처음</option><option value="secret-b">다음</option><option disabled>사용 불가</option></select></label><label>알림 받기<input id="notify" type="checkbox"></label><label>이메일<input id="email" type="email" required></label><select aria-label="계좌 정보"><option>민감 선택</option></select><select multiple aria-label="여러 선택"><option>A</option></select><button>제출</button></form><script>window.inputs=0;window.changes=0;window.submits=0;window.invalids=0;document.addEventListener('input',()=>window.inputs++);document.addEventListener('change',()=>window.changes++);document.addEventListener('invalid',()=>window.invalids++,true);</script>`;
test('Space selects options and checkbox state only on explicit apply; validity read never submits',async({context,servePage,expectNoExternalRequests})=>{
 test.setTimeout(150000);servePage('http://practice.test/controls.html',html);const page=await context.newPage();await page.goto('http://practice.test/controls.html');await startSwitch(page);await chooseSwitch(page,'글쓰기');await chooseSwitch(page,'양식 한 장 보기');
 const panel=page.locator('tremor-helper-root').locator('.switch-panel');
 await expect(panel.locator('.switch-choice[data-item-id^="form-field:"]')).toHaveText(['분류','알림 받기','이메일','여러 선택']);await expect(panel).not.toContainText('secret');await expect(panel).not.toContainText('처음');
 await chooseSwitch(page,'분류');await chooseSwitch(page,'다음');await expect(page.locator('#category')).toHaveValue('secret-a');
 await chooseSwitch(page,'선택값 적용');await expect(page.locator('#category')).toHaveValue('secret-b');
 await chooseSwitch(page,'다음 칸');await chooseSwitch(page,'체크하기');await expect(page.locator('#notify')).not.toBeChecked();await chooseSwitch(page,'체크 상태 적용');await expect(page.locator('#notify')).toBeChecked();
 await chooseSwitch(page,'다음 칸');await chooseSwitch(page,'입력 오류 읽기');await expect(panel).toContainText('필수 입력칸이에요. 값을 입력하세요');
 expect(await page.evaluate(()=>{const counters=window as unknown as Window & {inputs:number;changes:number;submits:number;invalids:number};return [counters.inputs,counters.changes,counters.submits,counters.invalids];})).toEqual([2,2,0,0]);expectNoExternalRequests();
});
test('changed choices and pause cancel application while text drafts and origin survive',async({context,servePage,serviceWorker})=>{
 test.setTimeout(150000);servePage('http://practice.test/controls-cancel.html',html);const page=await context.newPage();await page.goto('http://practice.test/controls-cancel.html');await startSwitch(page);await chooseSwitch(page,'글쓰기');await chooseSwitch(page,'새 문장');await chooseSwitch(page,'띄어쓰기');await chooseSwitch(page,'양식 한 장 보기');await chooseSwitch(page,'분류');await chooseSwitch(page,'다음');
 await page.locator('#category').evaluate((el:HTMLSelectElement)=>{const option=el.options[1];if(option)option.value='site-change';});await chooseSwitch(page,'선택값 적용');await expect(page.locator('#category')).toHaveValue('secret-a');
 const panel=page.locator('tremor-helper-root').locator('.switch-panel');await expect(panel).toContainText('선택칸이 바뀌었어요');
 await chooseSwitch(page,'양식 목록');await chooseSwitch(page,'알림 받기');await chooseSwitch(page,'체크하기');await chooseSwitch(page,'쉬기');await page.keyboard.press('Space');await page.waitForTimeout(125);await expect(page.locator('#notify')).not.toBeChecked();
 await chooseSwitch(page,'원래 화면으로');await expect(panel.locator('.switch-draft')).toContainText(' ');
 const storage=await serviceWorker.evaluate(async()=>JSON.stringify(await chrome.storage.local.get(null)));expect(storage).not.toContain('secret');expect(storage).not.toContain('site-change');
});
test('page item control opens its field with stable option pages and fits three viewports',async({context,servePage})=>{
 test.setTimeout(150000);const longOption='긴 선택 항목 '.repeat(25)+'마지막 선택 끝';servePage('http://practice.test/controls-page.html',html.replace('<option value="secret-a">처음</option>',`<option value="secret-a">${'W'.repeat(100)}</option>`).replace('<option value="secret-b">다음</option>','<option value="secret-b">다음</option>'+Array.from({length:12},(_,i)=>`<option>${i===9?longOption:`선택 ${String(i)}`}</option>`).join('')));const page=await context.newPage();await page.goto('http://practice.test/controls-page.html');await startSwitch(page);await chooseSwitch(page,'페이지 항목');await chooseSwitch(page,'분류');
 const panel=page.locator('tremor-helper-root').locator('.switch-panel');await expect(panel.locator('h2')).toContainText('선택 목록');await page.setViewportSize({width:360,height:800});const widths=await panel.locator('.switch-choices').evaluate(el=>({client:el.clientWidth,scroll:el.scrollWidth}));expect(widths.scroll).toBeLessThanOrEqual(widths.client);await chooseSwitch(page,'다음 선택 묶음');await chooseSwitch(page,`12. ${Array.from(longOption).slice(0,24).join('')}…`);const pages=[await panel.locator('.switch-draft').innerText()];while(await panel.locator('[data-item-id="control-preview-next"]').count()){await chooseSwitch(page,'다음 항목 읽기');pages.push(await panel.locator('.switch-draft').innerText());}expect(pages.map(text=>text.split('\n').slice(1).join('\n')).join('')).toBe(longOption);await expect(page.locator('#category')).toHaveValue('secret-a');
 for(const width of [360,768,1280]){
  await page.setViewportSize({width,height:800});const metrics=await panel.evaluate(el=>({right:el.getBoundingClientRect().right,bottom:el.getBoundingClientRect().bottom,previewFits:(el.querySelector('.switch-draft')?.scrollHeight??0)<=(el.querySelector('.switch-draft')?.clientHeight??0),choices:Array.from(el.querySelectorAll('.switch-choice')).map(choice=>({height:choice.getBoundingClientRect().height,font:parseFloat(getComputedStyle(choice).fontSize)}))}));expect(metrics.previewFits).toBe(true);expect(metrics.right).toBeLessThanOrEqual(width);expect(metrics.bottom).toBeLessThanOrEqual(800);for(const choice of metrics.choices){expect(choice.height).toBeGreaterThanOrEqual(56);expect(choice.font).toBeGreaterThanOrEqual(18);}await page.screenshot({path:`docs/verification/form-controls-${String(width)}.png`});
 }
});
test('automatic rest discards control proposal before resuming',async({context,servePage})=>{
 test.setTimeout(70000);servePage('http://practice.test/controls-rest.html',html);const page=await context.newPage();await page.goto('http://practice.test/controls-rest.html');await startSwitch(page);await chooseSwitch(page,'글쓰기');await chooseSwitch(page,'양식 한 장 보기');await chooseSwitch(page,'알림 받기');await chooseSwitch(page,'체크하기');
 const panel=page.locator('tremor-helper-root').locator('.switch-panel');await expect(panel).toHaveAttribute('data-mode','paused',{timeout:30000});await page.keyboard.press('Space');await page.waitForTimeout(125);await expect(panel.locator('[data-item-id="control-apply"]')).toHaveCount(0);await expect(page.locator('#notify')).not.toBeChecked();
});
test('lost apply acknowledgement pauses with uncertainty and does not repeat a completed change',async({context,serviceWorker,servePage})=>{
 test.setTimeout(70000);servePage('http://practice.test/controls-unknown.html',html);const page=await context.newPage();await page.goto('http://practice.test/controls-unknown.html');await startSwitch(page);await chooseSwitch(page,'글쓰기');await chooseSwitch(page,'양식 한 장 보기');await chooseSwitch(page,'알림 받기');await chooseSwitch(page,'체크하기');
 await serviceWorker.evaluate(()=>{const send=chrome.tabs.sendMessage.bind(chrome.tabs);chrome.tabs.sendMessage=async(tabId,message,options)=>{const reply=await send(tabId,message,options);if(typeof message==='object'&&message!==null&&'action' in message&&typeof message.action==='object'&&message.action!==null&&'kind' in message.action&&message.action.kind==='applyControl')return {result:'unknown'};return reply;};});
 await chooseSwitch(page,'체크 상태 적용');const panel=page.locator('tremor-helper-root').locator('.switch-panel');await expect(panel).toHaveAttribute('data-mode','paused');await expect(panel).toContainText('실행 결과를 확인하세요');await expect(page.locator('#notify')).toBeChecked();await page.keyboard.press('Space');await page.waitForTimeout(125);await expect(panel.locator('[data-item-id="control-apply"]')).toHaveCount(0);expect(await page.evaluate(()=>(window as Window & {changes?:number}).changes)).toBe(1);
});
test('late control capture after blur cannot reopen the field or apply a change',async({context,serviceWorker,servePage})=>{
 test.setTimeout(70000);servePage('http://practice.test/controls-late.html',html);const page=await context.newPage();await page.goto('http://practice.test/controls-late.html');await startSwitch(page);await chooseSwitch(page,'글쓰기');await chooseSwitch(page,'양식 한 장 보기');
 await serviceWorker.evaluate(()=>{const send=chrome.tabs.sendMessage.bind(chrome.tabs);const held=globalThis as typeof globalThis & {heldControl?:boolean;releaseControl?:()=>void};chrome.tabs.sendMessage=async(tabId,message,options)=>{const reply=await send(tabId,message,options);if(typeof message==='object'&&message!==null&&'action' in message&&typeof message.action==='object'&&message.action!==null&&'kind' in message.action&&message.action.kind==='captureControl'){held.heldControl=true;await new Promise<void>(resolve=>{held.releaseControl=resolve;});}return reply;};});
 await chooseSwitch(page,'분류');await expect.poll(()=>serviceWorker.evaluate(()=>(globalThis as typeof globalThis & {heldControl?:boolean}).heldControl)).toBe(true);await page.evaluate(()=>window.dispatchEvent(new Event('blur')));const panel=page.locator('tremor-helper-root').locator('.switch-panel');await expect(panel).toHaveAttribute('data-mode','paused');await serviceWorker.evaluate(()=>(globalThis as typeof globalThis & {releaseControl?:()=>void}).releaseControl?.());await page.waitForTimeout(400);await expect(panel).toHaveAttribute('data-mode','paused');await expect(panel.locator('[data-item-id="control-apply"]')).toHaveCount(0);await expect(panel.locator('.switch-draft')).toHaveCount(0);await expect(page.locator('#category')).toHaveValue('secret-a');
});
